name: hugo build and run checks

on:
  pull_request:

jobs:
  deploy:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true 
          fetch-depth: 0

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.133.1'
          extended: true

      - uses: actions/setup-go@v5
        with:
          go-version: "1.23"

      - name: Validate Swagger
        run: |
          go install github.com/go-swagger/go-swagger/cmd/swagger@latest
          swagger validate static/swagger.yml